import { UserProfile, SkillNode, MarketSkill, CareerGap, SprintRoadmap } from './types';

export const initialProfile: UserProfile = {
  userId: 'usr_somnath_aws',
  email: 'somnath@skillgraph.dev',
  name: 'Somnath',
  targetRole: 'Cloud Security Engineer',
  weeklyHoursCommitment: 8,
  careerReadiness: 68,
  marketAlignment: 74,
  evidenceStrength: 61,
  skillCoverage: 72,
  criticalGapsCount: 4,
  verifiedSkillsCount: 7,
  updatedAt: new Date().toISOString(),
};

export const availableTargetRoles = [
  'Cloud Security Engineer',
  'DevOps / SRE Engineer',
  'Cloud Solutions Architect',
  'Backend Distributed Systems Engineer',
  'AI Systems Engineer',
];

export const initialSkills: SkillNode[] = [
  {
    skillId: 'skl_python',
    name: 'Python',
    category: 'Engineering',
    selfReportedLevel: 'Advanced',
    evidenceStrength: 82,
    confidenceScore: 88,
    assessmentTier: 'Strong',
    evidenceCount: 4,
    verified: true,
    dependencies: [],
    downstreamUnlocks: ['skl_aws_sdk', 'skl_sec_automation'],
  },
  {
    skillId: 'skl_linux',
    name: 'Linux & Shell',
    category: 'Engineering',
    selfReportedLevel: 'Advanced',
    evidenceStrength: 79,
    confidenceScore: 85,
    assessmentTier: 'Strong',
    evidenceCount: 3,
    verified: true,
    dependencies: [],
    downstreamUnlocks: ['skl_docker', 'skl_security_operations'],
  },
  {
    skillId: 'skl_aws',
    name: 'AWS Core Services',
    category: 'Cloud',
    selfReportedLevel: 'Intermediate',
    evidenceStrength: 64,
    confidenceScore: 72,
    assessmentTier: 'Moderate',
    evidenceCount: 2,
    verified: true,
    dependencies: ['skl_cloud_basics'],
    downstreamUnlocks: ['skl_iam', 'skl_cloud_sec'],
  },
  {
    skillId: 'skl_docker',
    name: 'Docker & Containers',
    category: 'Engineering',
    selfReportedLevel: 'Intermediate',
    evidenceStrength: 62,
    confidenceScore: 70,
    assessmentTier: 'Moderate',
    evidenceCount: 2,
    verified: true,
    dependencies: ['skl_linux'],
    downstreamUnlocks: ['skl_k8s', 'skl_cloud_run'],
  },
  {
    skillId: 'skl_iam',
    name: 'AWS IAM & Least Privilege',
    category: 'Security',
    selfReportedLevel: 'Beginner',
    evidenceStrength: 31,
    confidenceScore: 40,
    assessmentTier: 'Weak',
    evidenceCount: 1,
    verified: false,
    dependencies: ['skl_aws'],
    downstreamUnlocks: ['skl_sec_architecture'],
  },
  {
    skillId: 'skl_terraform',
    name: 'Terraform & IaC',
    category: 'Cloud',
    selfReportedLevel: 'Beginner',
    evidenceStrength: 9,
    confidenceScore: 25,
    assessmentTier: 'Weak',
    evidenceCount: 0,
    verified: false,
    dependencies: ['skl_aws'],
    downstreamUnlocks: ['skl_cloud_sec_projects', 'skl_infra_automation'],
  },
  {
    skillId: 'skl_siem',
    name: 'SIEM & SOC Operations',
    category: 'Security',
    selfReportedLevel: 'Beginner',
    evidenceStrength: 18,
    confidenceScore: 30,
    assessmentTier: 'Weak',
    evidenceCount: 0,
    verified: false,
    dependencies: ['skl_linux'],
    downstreamUnlocks: ['skl_threat_hunting'],
  },
  {
    skillId: 'skl_k8s',
    name: 'Kubernetes',
    category: 'Engineering',
    selfReportedLevel: 'Intermediate',
    evidenceStrength: 17,
    confidenceScore: 20,
    assessmentTier: 'Insufficient',
    evidenceCount: 0,
    verified: false,
    dependencies: ['skl_docker'],
    downstreamUnlocks: ['skl_cloud_native_sec'],
  },
];

export const initialMarketSkills: MarketSkill[] = [
  {
    skillId: 'skl_aws_sec',
    skillName: 'AWS Security Services',
    demandScore: 91,
    frequencyPercentage: 88,
    trend: 'UP',
    trendSymbol: '↑',
    currentEvidenceScore: 45,
    isCriticalGap: true,
  },
  {
    skillId: 'skl_iam',
    skillName: 'AWS IAM',
    demandScore: 82,
    frequencyPercentage: 73,
    trend: 'UP',
    trendSymbol: '↑',
    currentEvidenceScore: 31,
    isCriticalGap: true,
  },
  {
    skillId: 'skl_python',
    skillName: 'Python',
    demandScore: 70,
    frequencyPercentage: 58,
    trend: 'STABLE',
    trendSymbol: '→',
    currentEvidenceScore: 81,
    isCriticalGap: false,
  },
  {
    skillId: 'skl_siem',
    skillName: 'SIEM & Monitoring',
    demandScore: 65,
    frequencyPercentage: 62,
    trend: 'UP',
    trendSymbol: '↑',
    currentEvidenceScore: 18,
    isCriticalGap: true,
  },
  {
    skillId: 'skl_terraform',
    skillName: 'Terraform',
    demandScore: 61,
    frequencyPercentage: 61,
    trend: 'UP_RAPID',
    trendSymbol: '↑↑',
    currentEvidenceScore: 9,
    isCriticalGap: true,
  },
  {
    skillId: 'skl_docker',
    skillName: 'Docker',
    demandScore: 55,
    frequencyPercentage: 42,
    trend: 'STABLE',
    trendSymbol: '→',
    currentEvidenceScore: 62,
    isCriticalGap: false,
  },
];

export const initialGaps: CareerGap[] = [
  {
    skillId: 'skl_terraform',
    skillName: 'Terraform & IaC',
    userScore: 9,
    marketDemand: 61,
    rawGap: 52,
    leverageMultiplier: 1.6,
    priorityRank: 1,
    downstreamUnlocks: ['AWS Infra Automation', 'Security Infrastructure', 'Cloud Sec Projects'],
  },
  {
    skillId: 'skl_iam',
    skillName: 'AWS IAM',
    userScore: 31,
    marketDemand: 82,
    rawGap: 51,
    leverageMultiplier: 1.4,
    priorityRank: 2,
    downstreamUnlocks: ['Least Privilege Arch', 'Cross-Account Roles'],
  },
  {
    skillId: 'skl_siem',
    skillName: 'SIEM Security Monitoring',
    userScore: 18,
    marketDemand: 65,
    rawGap: 47,
    leverageMultiplier: 1.2,
    priorityRank: 3,
    downstreamUnlocks: ['CloudWatch Alarms', 'SOC Triaging'],
  },
  {
    skillId: 'skl_aws_sec',
    skillName: 'AWS Security Services',
    userScore: 45,
    marketDemand: 91,
    rawGap: 46,
    leverageMultiplier: 1.1,
    priorityRank: 4,
    downstreamUnlocks: ['GuardDuty', 'Security Hub'],
  },
];

export function generateSprintRoadmap(hoursPerWeek: number, targetRole: string): SprintRoadmap {
  if (hoursPerWeek <= 5) {
    return {
      roadmapId: 'sprint_5h',
      targetRole,
      allocatedHoursPerWeek: 5,
      durationDays: 30,
      weeks: [
        {
          weekNumber: 1,
          phase: 'LEARN',
          focusSkill: 'Core IAM Policy Evaluation',
          deliverables: ['Read IAM policy grammar', 'Create 2 permission boundaries in AWS console'],
        },
        {
          weekNumber: 2,
          phase: 'LEARN',
          focusSkill: 'Terraform Fundamentals',
          deliverables: ['Install Terraform CLI', 'Write basic HCL for S3 bucket with encryption'],
        },
        {
          weekNumber: 3,
          phase: 'BUILD',
          focusSkill: 'Terraform IAM Module',
          deliverables: ['Declarative least-privilege role template', 'Run tfsec linter on code'],
        },
        {
          weekNumber: 4,
          phase: 'PROVE',
          focusSkill: 'GitHub Repository Artifact',
          deliverables: ['Push terraform-aws-iam-module to GitHub', 'Add README with architecture diagram'],
        },
      ],
      expectedOutcomes: [
        '✓ IAM Evidence: +25% boost',
        '✓ Terraform Evidence: +30% boost',
        '✓ 1 Verified Portfolio Repository',
      ],
    };
  }

  return {
    roadmapId: 'sprint_8h',
    targetRole,
    allocatedHoursPerWeek: hoursPerWeek,
    durationDays: 30,
    weeks: [
      {
        weekNumber: 1,
        phase: 'LEARN',
        focusSkill: 'AWS IAM Fundamentals & Delegation',
        deliverables: ['IAM least-privilege policies', 'Cross-account trust relationship logic'],
      },
      {
        weekNumber: 2,
        phase: 'BUILD',
        focusSkill: 'AWS Security Monitoring Architecture',
        deliverables: ['CloudTrail & CloudWatch log routing', 'Automated GuardDuty alert responder Lambda'],
      },
      {
        weekNumber: 3,
        phase: 'BUILD',
        focusSkill: 'Terraform Infrastructure Orchestration',
        deliverables: ['Complete modular IaC for security baseline', 'Automated security linting via tfsec in CI'],
      },
      {
        weekNumber: 4,
        phase: 'PROVE',
        focusSkill: 'Deploy, Document & Prove',
        deliverables: [
          'Deploy live to AWS sandbox',
          'Automate unit & compliance integration tests',
          'Publish GitHub showcase repo with design doc',
        ],
      },
    ],
    expectedOutcomes: [
      '✓ IAM Evidence: +45% boost (Strong tier)',
      '✓ Terraform Evidence: +50% boost (Moderate tier)',
      '✓ SIEM Evidence: +35% boost',
      '✓ Production-grade Portfolio Showcase Project',
    ],
  };
}
